version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_postgres
    
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PgAdmin
    restart: always
    environment:

      PGADMIN_DEFAULT_EMAIL: success123shrestha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5011:80
    depends_on:
      - postgres

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis_data
    ports:
      - 6379:6379
    depends_on:
      - postgres

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - 8082:8082
    depends_on:
      - redis 