version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_postgres
    
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   depends_on:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: success123shrestha@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - "8080:8080"

  # pgadmin:
  #   image: dpage/pgadmin4:4.18
  #   container_name:  PgAdmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: secret
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 5011:80
  #   # volumes:
  #   #   - pgadmin-data:/var/lib/pgadmin
  #   # links:
  #   #   - pgsql:pgsql-server
  #   depends_on:
  #     - postgres



  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: PgAdmin
    restart: always
    environment:

      PGADMIN_DEFAULT_EMAIL: success123shrestha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5011:80
    depends_on:
      - postgres
